---
version: 2
updates:
  # Uncomment when hugo_frontend reaches main.
  # package-ecosystem: 'gitsubmodule'                                           # git submodule
  # directory: '.'
  # rebase-strategy: 'auto'
  # reviewers: ['caseysparkz']
  # target-branch: 'main'
  # schedule:
  #   interval: 'weekly'
  #   day: 'friday'
  #   time: '18:30'
  #   timezone: 'America/Los_Angeles'
  # commit-message:
  #   prefix: 'chore(gitsubmodule)'

  - package-ecosystem: 'github-actions'                                         # github-actions
    directory: '.github/workflows'
    rebase-strategy: 'auto'
    reviewers: ['caseysparkz']
    target-branch: 'main'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '18:30'
      timezone: 'America/Los_Angeles'
    commit-message:
      prefix: 'chore(github_actions)'

  - package-ecosystem: 'terraform'                                              # terraform
    rebase-strategy: 'auto'
    reviewers: ['caseysparkz']
    target-branch: 'main'
    directories: [
      'tfstate_backend',
      'centripedalporch.com',
    ]
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '18:30'
      timezone: 'America/Los_Angeles'
    commit-message:
      prefix: 'chore(terraform)'
