---
version: '0.1'
projects:
  - name: &name 'centripedalporch.com'
    path: *name
    skip_autodetect: true
    usage_file: 'centripedalporch.com/.infracost_usage.yml'
    terraform_var_files: &default_vars ['production.tfvars']

  - name: &name 'tfstate_backend'
    path: *name
    skip_autodetect: true
    usage_file: 'tfstate_backend/.infracost_usage.yml'
    terraform_var_files: *default_vars
