# Author:       Casey Sparks
# Date:         February 25, 2025
# Description:  Ensures that commit titles adhere to the Conventional Commit syntax.
# Notes:        See https://www.conventionalcommits.org/en/v1.0.0/
---
name: 'Conventional Commits'
on: ['pull_request']
jobs:
  conventional_commits:
    name: 'Conventional Commits'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8'  # v5.0.0

      - name: 'Check conventional commit compliance'
        uses: 'webiny/action-conventional-commits@8bc41ff4e7d423d56fa4905f6ff79209a78776c7'  # v1.3.0
        with:
          GITHUB_TOKEN: '${{ github.token }}'
