# Author:       Casey Sparks
# Date:         February 25, 2025
# Description:  Hugo
---
name: 'Validate Hugo configuration'
on:
  pull_request:
    branches: ['main']
    paths: ['centripedalporch.com/frontends/www/**']
env:
  HUGO_VER: '0.143.1'
  HUGO_CACHE_DIR: '/tmp/hugo_cache'
jobs:
  hugo:
    name: 'Hugo'
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: 'centripedalporch.com/frontends/www/'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8'  # v5.0.0
        with:
          fetch-depth: 0

      - name: 'Set up Hugo'
        uses: 'peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f'  # v3.0.0
        with:
          hugo-version: '${{ env.HUGO_VER }}'
          extended: true

      - name: 'Install Hugo modules'
        run: 'hugo mod get --update'

      - name: 'Hugo Build'
        run: 'hugo --minify'
